name: Rift
version: 1.0
main: net.therift.Main
description: Core Plugin of The Rift
author: Muffin
website: therift.net
api-version: 1.16
commands:
  gmc:
    description: Alias for creative mode
  gms:
    description: Alias for survival mode
  gmss:
    description: Alias for spectator mode
depend: [ProtocolLib, NBTAPI]